27.1 the need for exceptions
- Exception handling provides a mechanism to decouple handling of errors or other exceptional circumstances from the typical control flow of your code. 
-  This allows more freedom to handle errors when and how ever is most useful for a given situation, alleviating most (if not all) of the messiness that return codes cause.

27.2 Basic Exception handling
- Exceptions in C++ are implemented using three keywords that work in conjunction with each other: throw, try, and catch.
- In C++, a throw statement is used to signal that an exception or error case has occurred (think of throwing a penalty flag).
   Signaling that an exception has occurred is also commonly called raising an exception.
- throw -1; // throw a literal integer value
  throw ENUM_INVALID_INDEX; // throw an enum value
  throw "Can not take square root of negative number"; // throw a literal C-style (const char*) string
  throw dX; // throw a double variable that was previously defined
  throw MyException("Fatal Error"); // Throw an object of class MyException
- try merely tells the program, “Hey, if any of the statements inside this try block throws an exception, grab it!”.
- Actually handling exceptions is the job of the catch block(s). 
  The catch keyword is used to define a block of code (called a catch block) that handles exceptions for a single data type.
- Catch parameters work just like function parameters, with the parameter being available within the subsequent catch block. Exceptions of fundamental types can be caught by value, but exceptions of non-fundamental types should be caught 
  by const reference to avoid making an unnecessary copy (and, in some cases, to prevent slicing).
- No type conversion is done for exceptions (so an int exception will not be converted to match a catch block with a double parameter).
- There are four common things that catch blocks do when they catch an exception:
  1) First, catch blocks may print an error (either to the console, or a log file) and then allow the function to proceed.
  2) Second, catch blocks may return a value or error code back to the caller.
  3) Third, a catch block may throw another exception. Because the catch block is outside of the try block, the newly thrown exception in this case is not handled by the preceding try block -- it’s handled by the next enclosing try block.
  4) Fourth, a catch block in main() may be used to catch fatal errors and terminate the program in a clean way.

27.3 Exceptions and functions, and stack unwinding
- Try blocks catch exceptions not only from statements within the try block, but also from functions that are called within the try block.
- Unwinding the stack destroys local variables in the functions that are unwound (which is good, because it ensures their destructors execute).

27.4 Uncaught exceptions and catch all handlers
- The call stack may or may not be unwound if an exception is unhandled.
- If the stack is not unwound, local variables will not be destroyed, which may cause problems if those variables have non-trivial destructors.
- catch-- all handlers
- Fortunately, C++ also provides us with a mechanism to catch all types of exceptions. This is known as a catch-all handler
- If your program uses exceptions, consider using a catch-all handler in main, to help ensure orderly behavior if an unhandled exception occurs.
- If an exception is caught by the catch-all handler, you should assume the program is now in some indeterminate state, perform cleanup immediately, and then terminate.
- Therefore, in debug builds, it can be useful to disable the catch-all handler. We can do this via conditional compilation directives.

27.5 Exceptions,classes and inheritance
- Constructors are another area of classes in which exceptions can be very useful. If a constructor must fail for some reason (e.g. the user passed in invalid input), 
  simply throw an exception to indicate the object failed to create.
-   Fortunately, the C++ standard library comes with RAII-compliant classes to manage common resource types, such as files
   (std::fstream, covered in lesson 28.6 -- Basic file I/O) and dynamic memory (std::unique_ptr and the other smart pointers)
- class Foo
  private:
    int * ptr;
- class Foo
  private:
   std::unique_ptr<int> ptr;// std::unique_ptr willl handle allocation/ deallocation
- Exceptions of a fundamental type can be caught by value since they are cheap to copy.
- Exceptions of a class type should be caught by (const) reference to prevent expensive copying and slicing.
- Handlers for derived exception classes should be listed before those for base classes.
- Exception objects need to be copyable.

27.6 Rethrowing Exceptions
- In this case, getIntValue() throws a Derived object, but the catch block is catching a Base reference. 
  This is fine, as we know we can have a Base reference to a Derived object. However, when we throw an exception, the thrown exception is 
  copy-initialized from variable exception. Variable exception has type Base, so the copy-initialized exception
- When rethrowing the same exception, use the throw keyword by itself

27.7 Function try blocks
- Use function try blocks when you need a constructor to handle an exception thrown in the member initializer list.
- Avoid letting control reach the end of a function-level catch block. Instead, explicitly throw, rethrow, or return.
- This means that you can’t use function try to clean up after a class. If you want to clean up after a class, follow the standard rules for cleaning up classes that throw exceptions 
  see the “When constructors fail” subsection of lesson 27.5 -- Exceptions, classes, and inheritance).
- Function try is useful primarily for either logging failures before passing the exception up the stack, or for changing the type of exception thrown.


27.8 Exception Dangers and downside
- The best option (whenever possible) is to prefer to stack allocate objects that implement RAII (automatically allocate resources on construction, deallocate resource on destruction). That way when the object managing the resource goes out of 
  scope for any reason, it will automatically deallocate as appropriate, so we don’t have to worry about such things!
- Destructors should not throw exceptions.
- Exception handling is best used when all of the following are true:
The error being handled is likely to occur only infrequently.
The error is serious and execution could not continue otherwise.
The error cannot be handled at the place where it occurs.
There isn’t a good alternative way to return an error code back to the caller.

27.9 Exception specification and no exception
- To define a function as non-throwing, we can use the noexcept specifier. 
  To do so, we use the noexcept keyword in the function declaration, placed to the right of the function parameter list:
- lways make move constructors, move assignment, and swap functions noexcept.

Make copy constructors and copy assignment operators noexcept when you can.

Use noexcept on other functions to express a no-fail or no-throw guarantee.
- 

27.10 std::move_if_noexcept
- 












